language: java
jdk:
  - oraclejdk8
env:
  - DITA_OT=3.1
before_script:
  - zip -r com.oxygenxml.editlink.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-3.1.zip
  - chmod +x dita-ot-3.1/bin/dita
  - dita-ot-3.1/bin/dita --install https://github.com/jason-fox/fox.jason.unit-test/archive/master.zip
  - dita-ot-3.1/bin/dita --install com.oxygenxml.editlink.zip
  - cp dita-ot-3.1/plugins/fox.jason.unit-test/resource/pom.xml pom.xml
  
script:
  - dita-ot-3.1/bin/dita --input dita-ot-3.1/plugins/com.oxygenxml.editlink -f xsl-instrument -v
  - dita-ot-3.1/bin/dita --input dita-ot-3.1/plugins/com.oxygenxml.editlink -f unit-test --output . -v
after_success:
  - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report