language: java
jdk:
  - oraclejdk8
env:
  - DITA_OT=3.1
before_script:
  - zip -r com.oxygenxml.editlink.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-$DITA_OT.zip
  - chmod +x dita-ot-$DITA_OT/bin/dita
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/fox.jason.unit-test/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita --install com.oxygenxml.editlink.zip 
script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/com.oxygenxml.editlink -f unit-test -v